### ISSUE TITLE
Platform Home dashboard

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#37]
**__User Story Summary__**
The main page after a user successfully signs in. It should show book recommendations. The list should be displayed horizontally in rows.

**__Stories__**
- [x] As a **user** I should be able to **see a slider with the latest books added**
- [x] As a **user** I should be able to **see suggested books by categories**
- [x] As a **user** I should be able to **see suggested books based on my saved books** _(at the top of the page, at most 2 rows)_

**__Test__**
Home dashboard shows lists of suggested books by categories and preferences, as well as latest books added

**__Additional Considerations__**

**Comment by sojelee** [comment]
As a user I should be able to navigate to the book details page

**Comment by Kerosz** [comment]
@sojelee Add that story as part of the issue description. You should be able to edit. Make sure to follow the same style/markdown
