### ISSUE TITLE
Setup CI pipelines

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#46]
**__Task Description__**
- [x] Setup Heroku CI pipeline for the initial back-end project
- [ ] Setup Vercel CI pipeline for the initial front-end project

**__Technical Considerations__**

**__Additional Considerations__**
[Heroku Docs](https://devcenter.heroku.com/categories/reference)
[Vercel Docs](https://vercel.com/docs)

**Comment by Bluette1** [comment]
@Kerosz, was deployment of the frontend on Netlify expected to be a part of this issue?

**Comment by Kerosz** [comment]
@Bluette1 Yes, deploying to netlify is part of the issue. Make sure that auto builds only run when you push to `main`, as far as I know Netlify has a limited build time a month, so we don't want to exceed the build limit, by building it every time we push to `develop` branch.

**Comment by Bluette1** [comment]
@Kerosz, Okay I will try to see how to change the auto builds on Netlify.

**Comment by Kerosz** [comment]
Added the CD for the BE, had some issues with heroku, therefor I made 3 fix commits.

**Comment by Bluette1** [comment]
Okay, great. I'll pick up another issue then. I think I've successfully managed to disable auto builds on the `develop` branch as well as deploy-previews on pull requests. Only merges to the `main` branch will be deployed.

**Comment by Kerosz** [comment]
Sounds good, then I'll be closing this issue.
