### ISSUE TITLE
Backend documentation & API documentation

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#70]
**__Task Description__**
Add backend code documentation and API documentation

**__Technical Considerations__**
Swagger and Compodoc can be used to automatically generate docs using NestJs builtin modules

**__Additional Considerations__**

**Comment by LuluNwenyi** [comment]
Hi @Kerosz are you proposing using postman or maybe a proper documentation using maybe gitbook??

**Comment by Kerosz** [comment]
Hello @LuluNwenyi this has already been addressed, currently using [swagger](https://swagger.io/) for the API documentation, and [compodoc](https://compodoc.app/) for the  BE code, being live here [docs.dekoo.tk](https://docs.dekoo.tk/)

Reason for the issue not being closed yet, it's because it's an **epic** spanning across sprints with the purpose of the team continuously adding the documentation and comments in the code for these tools to be able to extract it,
