### ISSUE TITLE
Serialize BE User response data

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v33-bears-team-15#82]
**__Task Description__**
User response data should only contain non sensitive fields. The current implementation exposes the following fields:

![image.png](https://images.zenhubusercontent.com/612ab08dfbb891568f6df72c/64ba32e2-c445-4a36-b447-176ab9d00abc)

**__Technical Considerations__**
User response should contain the following fields:
```json
    "wishList": [],
    "readingList": [],
    "role": "",
    "biography": "",
    "birthday": "",
    "avatar": "",
    "username": "",
    "_id": "",
    "email": "",
    "fullName": ""
```

**__Additional Considerations__**

**Comment by ArturoDucasse** [comment]
@Kerosz by serializing, do you mean to delete or just omit from this endpoint?

**Comment by Kerosz** [comment]
@ArturoDucasse I mean excluding properties, in short you can create a `UserEntity` class that defines all `user` fields, and use `@Exclude` for properties that we do not want to show.

Here is an example on nest docs: [Serialize Docs](https://docs.nestjs.com/techniques/serialization)
